### ISSUE TITLE
Backend Hosting

### ISSUE THREAD

**Issue by prateek-1606** [prateek-1606/Travelify#7]
Host Backend api on heroku asap

**Comment by Kushagrasri** [comment]
Treat hosting backend as top priority now

**Comment by AshishRaikwar1290** [comment]
I tried to host the backend on Heroku but pushing is reject by git
repository of Travelify.

**Comment by Kushagrasri** [comment]
Treat this as a production level issue and whole team try to resolve this on an urgent basis. We want a resolution before today EOD
